#!/bin/bash

# First of all, ensuring dependencies are installed and checking node_modules
if [ ! -d "node_modules" ]; then
    echo "Installing dependencies"
    if ! yarn install; then
        echo "Error: Dependencies failed to install"
        exit 1
    fi
fi

# We need docker and docker compose to be installed
if ! docker compose version; then
    echo "Error: Docker and docker compose are not installed: please refer to https://docs.docker.com/compose/install/"
    exit 1
fi

CLEAN=false
# Supporting cleanup of the database
if [ "$1" == "--clean" ]; then
    CLEAN=true
elif [ "$1" == "--help" ]; then
    echo "Usage: $0 [--clean]"
    exit 0
fi

# Database management
cd postgres
# Suppressing errors if the database is not running
docker compose down > /dev/null 2>&1
if [ "$CLEAN" == "true" ]; then
    sudo rm -rf data
    mkdir data
fi  
# Finally starting the database
docker compose up -d
cd ..

# Waiting for port 5332 to be available
echo -n "Waiting for the database to be available"
COUNT=0
while ! nc -z localhost 5332; do
    echo -n "."
    COUNT=$((COUNT+1))
    if [ $COUNT -gt 10 ]; then
        echo "Timeout waiting for the database to be available"
        exit 1
    fi
    sleep 1
done

# Starting the node managing errors
if ! yarn start; then
    echo "Error: RPC failed to start or crashed"
    exit_code=$?
else
    echo "RPC exited successfully"
    exit_code=0
fi

# Once exiting, stopping the database
cd postgres
docker compose down
cd ..