import { Entity, PrimaryColumn, Column } from "typeorm"

/**
 * L2PS Hashes Entity
 *
 * Stores L2PS UID → hash mappings for validator consensus.
 * Validators store ONLY these hash mappings and never see actual L2PS transaction content.
 * This preserves privacy while allowing validators to participate in consensus.
 *
 * @entity l2ps_hashes
 */
// REVIEW: New entity for Phase 3b - Validator Hash Storage
@Entity("l2ps_hashes")
export class L2PSHash {
    /**
     * L2PS network identifier (primary key)
     * Each L2PS network has one current hash mapping
     * @example "network_1", "private_subnet_alpha"
     */
    @PrimaryColumn("text")
    l2ps_uid: string

    /**
     * Consolidated hash of all transactions in this L2PS network
     * Generated by L2PSHashService every 5 seconds
     * @example "0xa1b2c3d4e5f6..."
     */
    @Column("text")
    hash: string

    /**
     * Number of transactions included in this consolidated hash
     * Used for monitoring and statistics
     */
    @Column("int")
    transaction_count: number

    /**
     * Block number when this hash was stored
     * Used for consensus and ordering
     */
    @Column("bigint", { default: 0 })
    block_number: bigint

    /**
     * Timestamp when this hash mapping was stored
     * Used for tracking updates and staleness detection
     */
    @Column("bigint")
    timestamp: bigint
}
