/* eslint-disable @typescript-eslint/naming-convention */
/**
 * Machine-readable error codes used across the application.
 *
 * Convention: DOMAIN_SPECIFIC_DESCRIPTION
 * - Prefix determines HTTP status in toErrorResponse()
 * - VALIDATION_ → 400, AUTH_ → 401, FORBIDDEN_ → 403,
 *   NOT_FOUND_ → 404, RATE_LIMIT_ → 429, TIMEOUT_ → 408
 */

export const ErrorCode = {
    // --- General ---
    UNKNOWN_ERROR: "UNKNOWN_ERROR",
    OPERATION_ABORTED: "OPERATION_ABORTED",

    // --- Timeout ---
    TIMEOUT_EXCEEDED: "TIMEOUT_EXCEEDED",

    // --- Validation ---
    VALIDATION_TYPE_ERROR: "VALIDATION_TYPE_ERROR",
    VALIDATION_RANGE_ERROR: "VALIDATION_RANGE_ERROR",
    VALIDATION_SYNTAX_ERROR: "VALIDATION_SYNTAX_ERROR",
    VALIDATION_BLOCK_INVALID: "VALIDATION_BLOCK_INVALID",
    VALIDATION_TX_INVALID: "VALIDATION_TX_INVALID",
    VALIDATION_FORMAT: "VALIDATION_FORMAT",

    // --- Auth ---
    AUTH_FAILED: "AUTH_FAILED",
    AUTH_INVALID_FORMAT: "AUTH_INVALID_FORMAT",

    // --- Not Found ---
    NOT_FOUND_BLOCK: "NOT_FOUND_BLOCK",
    NOT_FOUND_TX: "NOT_FOUND_TX",
    NOT_FOUND_PEER: "NOT_FOUND_PEER",
    NOT_FOUND_RESOURCE: "NOT_FOUND_RESOURCE",

    // --- Rate Limit ---
    RATE_LIMIT_EXCEEDED: "RATE_LIMIT_EXCEEDED",

    // --- Peer / Network ---
    PEER_UNREACHABLE: "PEER_UNREACHABLE",
    PEER_NOT_IN_SHARD: "PEER_NOT_IN_SHARD",
    PEER_DISCONNECTED: "PEER_DISCONNECTED",
    NETWORK_CONNECTION_FAILED: "NETWORK_CONNECTION_FAILED",
    NETWORK_TIMEOUT: "NETWORK_TIMEOUT",

    // --- Consensus ---
    CONSENSUS_FORGING_ENDED: "CONSENSUS_FORGING_ENDED",
    CONSENSUS_FAILED: "CONSENSUS_FAILED",

    // --- L2PS ---
    L2PS_BATCH_FAILED: "L2PS_BATCH_FAILED",
    L2PS_PROOF_FAILED: "L2PS_PROOF_FAILED",
    L2PS_SYNC_FAILED: "L2PS_SYNC_FAILED",

    // --- Storage / DB ---
    STORAGE_READ_FAILED: "STORAGE_READ_FAILED",
    STORAGE_WRITE_FAILED: "STORAGE_WRITE_FAILED",

    // --- OmniProtocol ---
    OMNI_UNKNOWN_OPCODE: "OMNI_UNKNOWN_OPCODE",
    OMNI_SIGNING_FAILED: "OMNI_SIGNING_FAILED",
    OMNI_CONNECTION_FAILED: "OMNI_CONNECTION_FAILED",
    OMNI_CONNECTION_TIMEOUT: "OMNI_CONNECTION_TIMEOUT",
    OMNI_POOL_CAPACITY: "OMNI_POOL_CAPACITY",

    // --- Identity ---
    IDENTITY_VERIFICATION_FAILED: "IDENTITY_VERIFICATION_FAILED",
    IDENTITY_PROVIDER_ERROR: "IDENTITY_PROVIDER_ERROR",

    // --- TLSNotary ---
    TLSN_PROOF_FAILED: "TLSN_PROOF_FAILED",
    TLSN_PROXY_ERROR: "TLSN_PROXY_ERROR",

    // --- MCP ---
    MCP_NOT_INITIALIZED: "MCP_NOT_INITIALIZED",
    MCP_ALREADY_RUNNING: "MCP_ALREADY_RUNNING",

    // --- Multichain ---
    MULTICHAIN_UNSUPPORTED: "MULTICHAIN_UNSUPPORTED",
    MULTICHAIN_BRIDGE_FAILED: "MULTICHAIN_BRIDGE_FAILED",

    // --- Transaction ---
    TX_REFERENCE_BLOCK_OUT_OF_RANGE: "TX_REFERENCE_BLOCK_OUT_OF_RANGE",
    TX_NONCE_INVALID_LOW: "TX_NONCE_INVALID_LOW",
    TX_NONCE_INVALID_HIGH: "TX_NONCE_INVALID_HIGH",
    TX_ALREADY_EXECUTED: "TX_ALREADY_EXECUTED",
    TX_EXECUTE_FAILED: "TX_EXECUTE_FAILED",
} as const

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode]
