import { Column, Entity, Index, PrimaryColumn } from "typeorm"
import type { SerializedEncryptedMessage } from "../types"

// Composite indexes documented on the entity for clarity — the actual
// CREATE INDEX statements live in migration
// `CreateL2PSMessagesTable1781556000000` because `synchronize: false`
// means TypeORM does not auto-emit them. Both cover the hot read paths:
//   - getQueuedMessages: WHERE to_key=$1 AND l2ps_uid=$2 AND status='queued' ORDER BY timestamp ASC
//   - getHistory:        WHERE l2ps_uid=$1 AND (from_key=$2 OR to_key=$2) ORDER BY timestamp DESC
@Index("IDX_l2ps_messages_queued_for_recipient", ["toKey", "l2psUid", "status", "timestamp"])
@Index("IDX_l2ps_messages_pair_history", ["l2psUid", "timestamp"])
@Entity("l2ps_messages")
export class L2PSMessage {
    /** UUID v4 generated by sender */
    @PrimaryColumn("text", { name: "id" })
    id: string

    @Index()
    @Column("text", { name: "from_key" })
    fromKey: string

    @Index()
    @Column("text", { name: "to_key" })
    toKey: string

    @Index()
    @Column("text", { name: "l2ps_uid" })
    l2psUid: string

    @Column("text", { name: "message_hash", unique: true })
    messageHash: string

    @Column("jsonb", { name: "encrypted" })
    encrypted: SerializedEncryptedMessage

    /** L2PS transaction hash once submitted to mempool */
    @Column("text", { name: "l2ps_tx_hash", nullable: true })
    l2psTxHash: string | null

    @Column("bigint", { name: "timestamp" })
    timestamp: string

    @Column("text", { name: "status", default: "delivered" })
    status: "delivered" | "queued" | "sent" | "l2ps_pending" | "l2ps_batched" | "l2ps_confirmed" | "failed"
}
