import { Column, Entity, Index, PrimaryColumn } from "typeorm"
import type { SerializedEncryptedMessage } from "../types"

@Entity("l2ps_messages")
export class L2PSMessage {
    /** UUID v4 generated by sender */
    @PrimaryColumn("text", { name: "id" })
    id: string

    @Index()
    @Column("text", { name: "from_key" })
    fromKey: string

    @Index()
    @Column("text", { name: "to_key" })
    toKey: string

    @Index()
    @Column("text", { name: "l2ps_uid" })
    l2psUid: string

    @Column("text", { name: "message_hash", unique: true })
    messageHash: string

    @Column("jsonb", { name: "encrypted" })
    encrypted: SerializedEncryptedMessage

    /** L2PS transaction hash once submitted to mempool */
    @Column("text", { name: "l2ps_tx_hash", nullable: true })
    l2psTxHash: string | null

    @Column("bigint", { name: "timestamp" })
    timestamp: string

    @Column("text", { name: "status", default: "delivered" })
    status: "delivered" | "queued" | "sent" | "l2ps_pending" | "l2ps_batched" | "l2ps_confirmed" | "failed"
}
