#!/bin/bash
mkdir -p node/data/keystore
npx --yes quorum-genesis-tool --consensus qbft --chainID 53550 --blockperiod 5 --requestTimeout 10 --epochLength 30000 --difficulty 1 --gasLimit '0xFFFFFF' --coinbase '0x0000000000000000000000000000000000000000' --validators 1 --members 0 --bootnodes 0 --outputPath 'artifacts'
cd artifacts
files=(*)
artifacts_subdir="${files[0]}"
mv $artifacts_subdir/* .
rm -rf $artifacts_subdir
# Moving the files
cd goQuorum
export my_ip=$(curl icanhazip.com)
echo "Node IP: $my_ip"
# Replacing <HOST> in static_nodes.json with your IP address
sed -i "s/<HOST>/$my_ip/g" static-nodes.json
# Copying files to node directory
cp static-nodes.json genesis.json ../../node/data/
cd ../validator0 && cp nodekey* address ../../node/data/
cp account* ../../node/data/keystore/
cd ../../node/ && geth --datadir data init data/genesis.json
rm -rf ../../artifacts
# Find a way to add validators on the fly (prolly with DEMOS)
