version: "3.7"
services:
    kyntainer-1:
        image: kyntainer
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - ./node_base:/node
            - ./node_1/.demos_identity:/node/.demos_identity
            - ./node_1/data/chain.db:/node/data/chain.db
            - ./node_1/pubkey:/node/pubkey
            - ./resources/peerlist:/node/demos_peers
        ports:
            # trunk-ignore(yamllint/quoted-strings)
            - "53551:53550"
        command: yarn run start:up