version: "3.7"
services:
    kyntainer-2:
        image: kyntainer
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - ./node_base:/node
            - ./node_2/.demos_identity:/node/.demos_identity
            - ./node_2/data/chain.db:/node/data/chain.db
            - ./node_2/pubkey:/node/pubkey
            - ./resources/peerlist:/node/demos_peers
        ports:
            # trunk-ignore(yamllint/quoted-strings)
            - "53552:53550"
        command: yarn run start:up