version: "3.7"
services:
    kyntainer-2:
        image: kyntainer
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - ./node_2:/node
            - ./resources/peerlist:/node/demos_peers
        ports:
            # trunk-ignore(yamllint/quoted-strings)
            - "53552:53550"
        command: yarn run start:up