/**
 * Environment variable name constants.
 *
 * Every process.env key used by the application is listed here.
 * No magic strings — import EnvKey instead of writing "PROD" directly.
 *
 * Convention: grouped by domain, matching the AppConfig sections.
 */

export const EnvKey = {
    // --- Server & Ports ---
    SERVER_PORT: "SERVER_PORT",
    RPC_PORT: "RPC_PORT",
    RPC_PG_PORT: "RPC_PG_PORT",
    SIGNALING_SERVER_PORT: "SIGNALING_SERVER_PORT",
    RPC_SIGNALING_PORT: "RPC_SIGNALING_PORT",
    MCP_SERVER_PORT: "MCP_SERVER_PORT",
    RPC_MCP_PORT: "RPC_MCP_PORT",
    OMNI_PORT: "OMNI_PORT",

    // --- Database (PostgreSQL) ---
    PG_HOST: "PG_HOST",
    PG_PORT: "PG_PORT",
    PG_USER: "PG_USER",
    PG_PASSWORD: "PG_PASSWORD",
    PG_DATABASE: "PG_DATABASE",

    // --- Core Node ---
    PROD: "PROD",
    SHARD_SIZE: "SHARD_SIZE",
    MAIN_LOOP_SLEEP_TIME: "MAIN_LOOP_SLEEP_TIME",
    RPC_FEE_PERCENT: "RPC_FEE_PERCENT",
    RPC_FEE: "RPC_FEE",
    NETWORK_FEE: "NETWORK_FEE",
    BURN_FEE: "BURN_FEE",
    MIN_VALIDATOR_STAKE: "MIN_VALIDATOR_STAKE",
    IDENTITY_FILE: "IDENTITY_FILE",
    PEER_LIST_FILE: "PEER_LIST_FILE",
    EXPOSED_URL: "EXPOSED_URL",
    SUDO_PUBKEY: "SUDO_PUBKEY",
    MAX_MESSAGE_SIZE: "MAX_MESSAGE_SIZE",
    CONSENSUS_CHECK_INTERVAL: "CONSENSUS_CHECK_INTERVAL",
    CONSENSUS_TIME: "CONSENSUS_TIME",
    LOG_LEVEL: "LOG_LEVEL",
    WHITELISTED_IPS: "WHITELISTED_IPS",
    WHITELISTED_KEYS: "WHITELISTED_KEYS",
    MCP_ENABLED: "MCP_ENABLED",
    RESTORE: "RESTORE",

    // --- TLSNotary ---
    TLSNOTARY_ENABLED: "TLSNOTARY_ENABLED",
    TLSNOTARY_HOST: "TLSNOTARY_HOST",
    TLSNOTARY_PORT: "TLSNOTARY_PORT",
    TLSNOTARY_SIGNING_KEY: "TLSNOTARY_SIGNING_KEY",
    TLSNOTARY_FATAL: "TLSNOTARY_FATAL",
    TLSNOTARY_DEBUG: "TLSNOTARY_DEBUG",
    TLSNOTARY_PROXY: "TLSNOTARY_PROXY",
    TLSNOTARY_DISABLED: "TLSNOTARY_DISABLED",
    TLSNOTARY_MODE: "TLSNOTARY_MODE",
    TLSNOTARY_MAX_SENT_DATA: "TLSNOTARY_MAX_SENT_DATA",
    TLSNOTARY_MAX_RECV_DATA: "TLSNOTARY_MAX_RECV_DATA",
    TLSNOTARY_AUTO_START: "TLSNOTARY_AUTO_START",
    TLSNOTARY_PROXY_PORT: "TLSNOTARY_PROXY_PORT",

    // --- OmniProtocol ---
    OMNI_ENABLED: "OMNI_ENABLED",
    OMNI_FATAL: "OMNI_FATAL",
    OMNI_MODE: "OMNI_MODE",
    OMNI_TLS_ENABLED: "OMNI_TLS_ENABLED",
    OMNI_TLS_MODE: "OMNI_TLS_MODE",
    OMNI_CERT_PATH: "OMNI_CERT_PATH",
    OMNI_KEY_PATH: "OMNI_KEY_PATH",
    OMNI_CA_PATH: "OMNI_CA_PATH",
    OMNI_TLS_MIN_VERSION: "OMNI_TLS_MIN_VERSION",
    OMNI_RATE_LIMIT_ENABLED: "OMNI_RATE_LIMIT_ENABLED",
    OMNI_MAX_CONNECTIONS_PER_IP: "OMNI_MAX_CONNECTIONS_PER_IP",
    OMNI_MAX_REQUESTS_PER_SECOND_PER_IP: "OMNI_MAX_REQUESTS_PER_SECOND_PER_IP",
    OMNI_MAX_REQUESTS_PER_SECOND_PER_IDENTITY: "OMNI_MAX_REQUESTS_PER_SECOND_PER_IDENTITY",

    // --- L2PS ---
    L2PS_ZK_ENABLED: "L2PS_ZK_ENABLED",
    L2PS_ZK_USE_MAIN_THREAD: "L2PS_ZK_USE_MAIN_THREAD",
    L2PS_HASH_INTERVAL_MS: "L2PS_HASH_INTERVAL_MS",
    L2PS_AGGREGATION_INTERVAL_MS: "L2PS_AGGREGATION_INTERVAL_MS",
    L2PS_MIN_BATCH_SIZE: "L2PS_MIN_BATCH_SIZE",
    L2PS_MAX_BATCH_SIZE: "L2PS_MAX_BATCH_SIZE",
    L2PS_CLEANUP_AGE_MS: "L2PS_CLEANUP_AGE_MS",

    // --- Metrics ---
    METRICS_ENABLED: "METRICS_ENABLED",
    METRICS_PORT: "METRICS_PORT",
    METRICS_HOST: "METRICS_HOST",

    // --- Diagnostics ---
    MIN_CPU_SPEED: "MIN_CPU_SPEED",
    MIN_RAM: "MIN_RAM",
    MIN_DISK_SPACE: "MIN_DISK_SPACE",
    MIN_NETWORK_DOWNLOAD_SPEED: "MIN_NETWORK_DOWNLOAD_SPEED",
    MIN_NETWORK_UPLOAD_SPEED: "MIN_NETWORK_UPLOAD_SPEED",
    NETWORK_TEST_FILE_SIZE: "NETWORK_TEST_FILE_SIZE",
    SUGGESTED_CPU_SPEED: "SUGGESTED_CPU_SPEED",
    SUGGESTED_RAM: "SUGGESTED_RAM",
    SUGGESTED_DISK_SPACE: "SUGGESTED_DISK_SPACE",
    SUGGESTED_NETWORK_DOWNLOAD_SPEED: "SUGGESTED_NETWORK_DOWNLOAD_SPEED",
    SUGGESTED_NETWORK_UPLOAD_SPEED: "SUGGESTED_NETWORK_UPLOAD_SPEED",

    // --- Identity & Web2 ---
    GITHUB_TOKEN: "GITHUB_TOKEN",
    DISCORD_API_URL: "DISCORD_API_URL",
    DISCORD_BOT_TOKEN: "DISCORD_BOT_TOKEN",
    HUMAN_PASSPORT_API_URL: "HUMAN_PASSPORT_API_URL",
    HUMAN_PASSPORT_SCORER_ID: "HUMAN_PASSPORT_SCORER_ID",
    HUMAN_PASSPORT_API_KEY: "HUMAN_PASSPORT_API_KEY",
    NOMIS_API_BASE_URL: "NOMIS_API_BASE_URL",
    NOMIS_DEFAULT_SCORE_TYPE: "NOMIS_DEFAULT_SCORE_TYPE",
    NOMIS_DEFAULT_DEADLINE_OFFSET_SECONDS: "NOMIS_DEFAULT_DEADLINE_OFFSET_SECONDS",
    NOMIS_API_KEY: "NOMIS_API_KEY",
    NOMIS_CLIENT_ID: "NOMIS_CLIENT_ID",
    NOMIS_API_TIMEOUT_MS: "NOMIS_API_TIMEOUT_MS",
    ETHERSCAN_API_KEY: "ETHERSCAN_API_KEY",
    HELIUS_API_KEY: "HELIUS_API_KEY",
    RAPID_API_KEY: "RAPID_API_KEY",
    RAPID_API_HOST: "RAPID_API_HOST",
    SOLANA_RPC: "SOLANA_RPC",
    ZK_ATTESTATION_POINTS: "ZK_ATTESTATION_POINTS",

    // --- Bridges ---
    RUBIC_API_REFERRER_ADDRESS: "RUBIC_API_REFERRER_ADDRESS",
    RUBIC_API_INTEGRATOR_ADDRESS: "RUBIC_API_INTEGRATOR_ADDRESS",

    // --- IPFS ---
    IPFS_SWARM_PORT: "IPFS_SWARM_PORT",
    IPFS_API_PORT: "IPFS_API_PORT",
} as const

export type EnvKey = (typeof EnvKey)[keyof typeof EnvKey]
