import * as anchor from "@coral-xyz/anchor"
import { Program, AnchorProvider, Wallet } from "@coral-xyz/anchor"
import { Connection, PublicKey, Keypair, SystemProgram } from "@solana/web3.js"
import { TOKEN_PROGRAM_ID, getAssociatedTokenAddress } from "@solana/spl-token"
import log from "@/utilities/logger"

// Import the IDL type (this should be generated by Anchor)
// TODO: Update path when IDL is properly generated and available
// import { SolanaTank } from "../SolanaTankProgram/solana_tank/target/types/solana_tank"

interface SolanaTankConfig {
    programId: PublicKey
    connection: Connection
    program: Program<any> // TODO: Replace 'any' with SolanaTank IDL type
    multisigPda: PublicKey
    network: string
}

interface SolanaTransactionResult {
    signature: string
    confirmed: boolean
}

/**
 * Manages Solana tank programs for native bridge operations
 * Handles USDC SPL token deposits, withdrawals, and multisig operations
 */
export class SolanaSmartContractManagement {
    private static instance: SolanaSmartContractManagement
    private tanks: Map<string, SolanaTankConfig> = new Map() // networkKey -> TankConfig
    private isInitialized = false

    // REVIEW Using singleton pattern for Solana tank management
    public static getInstance(): SolanaSmartContractManagement {
        if (!this.instance) {
            this.instance = new SolanaSmartContractManagement()
        }
        return this.instance
    }

    private constructor() {
        // Initialize will be called separately
    }

    /**
     * Initialize Solana tank management with deployed program addresses
     * @param programAddresses Map of networkKey -> program public key
     */
    public async initialize(programAddresses: { [networkKey: string]: string }): Promise<void> {
        if (this.isInitialized) {
            log.warning("SolanaSmartContractManagement already initialized")
            return
        }

        try {
            // Initialize each Solana network
            for (const [networkKey, programAddress] of Object.entries(programAddresses)) {
                if (networkKey.includes("solana") && programAddress !== "000000000000000000000000000000000000000000") {
                    await this.initializeSolanaTank(networkKey, programAddress)
                }
            }

            this.isInitialized = true
            log.info(`Initialized ${this.tanks.size} Solana tanks`)
        } catch (error) {
            log.error("Failed to initialize SolanaSmartContractManagement:" + error)
            throw error
        }
    }

    /**
     * Initialize a single Solana tank for a specific network
     * @param networkKey Format: "solana.devnet" or "solana.mainnet"
     * @param programAddress Program public key string
     */
    private async initializeSolanaTank(networkKey: string, programAddress: string): Promise<void> {
        const [chainName, network] = networkKey.split(".")
        
        if (chainName !== "solana") {
            throw new Error(`Invalid network key for Solana: ${networkKey}`)
        }

        try {
            // Get RPC URL based on network
            const rpcUrl = this.getSolanaRpcUrl(network)
            const connection = new Connection(rpcUrl, "confirmed")

            // Create program ID
            const programId = new PublicKey(programAddress)

            // Create a dummy wallet for read-only operations
            const dummyKeypair = Keypair.generate()
            const wallet = new anchor.Wallet(dummyKeypair)
            const provider = new AnchorProvider(connection, wallet, {
                commitment: "confirmed",
            })

            // TODO: Load actual IDL when available
            // For now, create a basic program instance
            // const program = new Program(idl, programId, provider) as Program<SolanaTank>
            const program = { programId, provider } as any // Placeholder

            // Derive the multisig PDA (assuming standard derivation)
            const [multisigPda] = PublicKey.findProgramAddressSync(
                [Buffer.from("multisig")],
                programId,
            )

            // Store tank configuration
            this.tanks.set(networkKey, {
                programId,
                connection,
                program,
                multisigPda,
                network,
            })

            log.info(`Solana tank initialized: ${networkKey} at ${programAddress}`)
        } catch (error) {
            log.error(`Failed to initialize Solana tank for ${networkKey}:` + error)
            throw error
        }
    }

    /**
     * Get Solana RPC URL based on network
     * @param network Network name (devnet, mainnet, testnet)
     * @returns RPC URL
     */
    private getSolanaRpcUrl(network: string): string {
        const rpcUrls = {
            devnet: "https://api.devnet.solana.com",
            mainnet: "https://api.mainnet-beta.solana.com", 
            testnet: "https://api.testnet.solana.com",
        }

        return rpcUrls[network as keyof typeof rpcUrls] || rpcUrls.devnet
    }

    /**
     * Get USDC SPL token balance in a Solana tank
     * @param networkKey Network identifier (e.g., "solana.devnet")
     * @returns USDC balance as string
     */
    public async getUSDCBalance(networkKey: string): Promise<string> {
        const tankConfig = this.tanks.get(networkKey)
        if (!tankConfig) {
            throw new Error(`Solana tank not found for network: ${networkKey}`)
        }

        try {
            // Get USDC mint address for this network
            const usdcMintAddress = this.getUSDCMintAddress(tankConfig.network)
            
            // Get associated token account for the tank multisig
            const tankTokenAccount = await getAssociatedTokenAddress(
                new PublicKey(usdcMintAddress),
                tankConfig.multisigPda,
                true, // Allow owner off curve
            )

            // Get token account balance
            const balance = await tankConfig.connection.getTokenAccountBalance(tankTokenAccount)
            return balance.value.amount
        } catch (error) {
            log.error(`Failed to get USDC balance for ${networkKey}:` + error)
            throw error
        }
    }

    /**
     * Get USDC mint address for a Solana network
     * @param network Network name
     * @returns USDC mint public key string
     */
    private getUSDCMintAddress(network: string): string {
        const usdcMints = {
            devnet: "4zMMC9srt5Ri5X14GAgXhaHii3GnPAEERYPJgZJDncDU", // USDC devnet mint
            mainnet: "EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v", // USDC mainnet mint
            testnet: "4zMMC9srt5Ri5X14GAgXhaHii3GnPAEERYPJgZJDncDU", // Same as devnet
        }

        return usdcMints[network as keyof typeof usdcMints] || usdcMints.devnet
    }

    /**
     * Verify a USDC deposit transaction on Solana
     * @param networkKey Network identifier
     * @param signature Transaction signature
     * @param expectedAmount Expected deposit amount
     * @param expectedSender Expected sender address
     * @returns Validation result
     */
    public async verifyDeposit(
        networkKey: string,
        signature: string,
        expectedAmount: string,
        expectedSender: string,
    ): Promise<{ valid: boolean; actualAmount?: string; actualSender?: string }> {
        const tankConfig = this.tanks.get(networkKey)
        if (!tankConfig) {
            throw new Error(`Solana tank not found for network: ${networkKey}`)
        }

        try {
            // Get transaction details
            const transaction = await tankConfig.connection.getTransaction(signature, {
                commitment: "confirmed",
                maxSupportedTransactionVersion: 0,
            })

            if (!transaction || !transaction.meta) {
                return { valid: false }
            }

            // Check if transaction was successful
            if (transaction.meta.err) {
                return { valid: false }
            }

            // Get USDC mint address
            const usdcMintAddress = this.getUSDCMintAddress(tankConfig.network)
            const usdcMint = new PublicKey(usdcMintAddress)

            // Get expected tank token account
            const tankTokenAccount = await getAssociatedTokenAddress(
                usdcMint,
                tankConfig.multisigPda,
                true,
            )

            // Parse token balances to verify USDC transfer to tank
            const preBalances = transaction.meta.preTokenBalances || []
            const postBalances = transaction.meta.postTokenBalances || []

            // Look for USDC transfers to the tank in the token balance changes
            // We'll check all token balance changes for ones involving the tank token account
            let transferredAmount = 0
            let foundTankTransfer = false

            for (const postBalance of postBalances) {
                if (postBalance.mint === usdcMintAddress) {
                    // Find corresponding pre-balance
                    const preBalance = preBalances.find(pre => 
                        pre.accountIndex === postBalance.accountIndex && pre.mint === usdcMintAddress,
                    )

                    if (preBalance) {
                        const preAmount = parseInt(preBalance.uiTokenAmount.amount)
                        const postAmount = parseInt(postBalance.uiTokenAmount.amount)
                        const amountChange = postAmount - preAmount

                        // Check if this is a positive transfer (deposit) to what could be our tank
                        if (amountChange > 0 && amountChange.toString() === expectedAmount) {
                            transferredAmount = amountChange
                            foundTankTransfer = true
                            break
                        }
                    }
                }
            }

            // Verify amount matches expected
            if (foundTankTransfer && transferredAmount.toString() === expectedAmount) {
                return {
                    valid: true,
                    actualAmount: transferredAmount.toString(),
                    actualSender: expectedSender, // Would need to parse from transaction instructions
                }
            }

            return { valid: false }
        } catch (error) {
            log.error(`Failed to verify Solana deposit for ${networkKey}:` + error)
            return { valid: false }
        }
    }

    /**
     * Execute USDC withdrawal from Solana tank (called by consensus)
     * @param networkKey Network identifier
     * @param recipient Recipient address
     * @param amount Amount in USDC smallest units
     * @param signerKeypairs Array of shard member keypairs
     */
    public async executeWithdrawal(
        networkKey: string,
        recipient: string,
        amount: string,
        signerKeypairs: Keypair[],
    ): Promise<string> {
        const tankConfig = this.tanks.get(networkKey)
        if (!tankConfig) {
            throw new Error(`Solana tank not found for network: ${networkKey}`)
        }

        try {
            // Get USDC mint address
            const usdcMintAddress = this.getUSDCMintAddress(tankConfig.network)
            const usdcMint = new PublicKey(usdcMintAddress)

            // Get tank and recipient token accounts
            const tankTokenAccount = await getAssociatedTokenAddress(
                usdcMint,
                tankConfig.multisigPda,
                true,
            )
            const recipientTokenAccount = await getAssociatedTokenAddress(
                usdcMint,
                new PublicKey(recipient),
            )

            // TODO: Create actual withdrawal transaction using the Solana tank program
            // This would involve creating a multisig proposal and having signers approve it
            // For now, returning a placeholder signature

            const placeholderSignature = "placeholder_withdrawal_signature"

            log.info(`USDC withdrawal executed on Solana ${networkKey}: ${amount} to ${recipient}`)
            return placeholderSignature
        } catch (error) {
            log.error(`Failed to execute Solana withdrawal on ${networkKey}:` + error)
            throw error
        }
    }

    /**
     * Get tank configuration for a network
     * @param networkKey Network identifier
     * @returns Tank configuration or null
     */
    public getTankConfig(networkKey: string): SolanaTankConfig | null {
        return this.tanks.get(networkKey) || null
    }

    /**
     * Get all supported Solana networks
     * @returns Array of supported network keys
     */
    public getSupportedNetworks(): string[] {
        return Array.from(this.tanks.keys())
    }

    /**
     * Check if the management system is properly initialized
     * @returns Initialization status
     */
    public isReady(): boolean {
        return this.isInitialized && this.tanks.size > 0
    }

    /**
     * Get status of all Solana tanks
     * @returns Status information for all tanks
     */
    public async getStatusReport(): Promise<{
        [networkKey: string]: {
            programId: string
            multisigPda: string
            usdcBalance: string
            network: string
        }
    }> {
        const report: any = {}
        
        for (const [networkKey, config] of this.tanks) {
            try {
                report[networkKey] = {
                    programId: config.programId.toString(),
                    multisigPda: config.multisigPda.toString(),
                    usdcBalance: await this.getUSDCBalance(networkKey),
                    network: config.network,
                }
            } catch (error) {
                report[networkKey] = {
                    programId: config.programId.toString(),
                    error: error,
                }
            }
        }
        
        return report
    }
}